<?php

/**
 * @file
 * Functions to support theming in the neo theme.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityFormInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityPublishedInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function neo_back_theme() {
  return [
    'entity_edit_form' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for \Drupal\node\NodeForm.
 *
 * Changes vertical tabs to container.
 */
function neo_back_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\Core\Entity\EntityFormInterface $form_object */
  $form_object = $form_state->getFormObject();
  if ($form_object instanceof EntityFormInterface) {
    $entity = $form_object->getEntity();
    if ($entity instanceof ContentEntityInterface && !isset($form['#neo_entity_form'])) {
      $form['#neo_entity_form'] = TRUE;
      $entity = $form_object->getEntity();
      $form['#theme'] = 'entity_edit_form';
      neo_back_form_meta($form, $form_state, $entity);
    }
  }
  // Only apply if we have no neo style set.
  $form['#neo_style'] = $form['#neo_style'] ?? 'card';

  switch ($form_id) {
    case 'user_admin_permissions':
    case 'better_permissions_page_user_admin_permissions':
      $form['permissions']['#sticky'] = TRUE;
      $form['actions']['#neo_style'] = 'sticky';
      break;

    case 'entity_form_display_edit_form':
    case 'entity_view_display_edit_form':
      $form['fields']['#neo_style'] = [
        0 => 'heading',
        1 => 'xs',
      ];
      $form['fields']['#neo_size'] = [
        0 => 'min',
        1 => 'min',
      ];
      break;
  }
}

function neo_back_preprocess_commerce_order__admin(array &$variables) {
  /** @var \Drupal\commerce_order\Entity\OrderInterface $order */
  $order = $variables['order_entity'];
  $variables['meta_color'] = match($order->getState()->getId()) {
    'draft' => 'bg-base-500 text-base-500-content',
    'canceled' => 'bg-error-500 text-error-500-content',
    default => 'bg-success-500 text-success-500-content',
  };
  // $variables['attributes']->addClass('p-card');
}

/**
 * Implements meta alterations.
 */
function neo_back_form_meta(&$form, FormStateInterface $form_state, EntityInterface $entity) {
  if (!empty($form['status']) && empty($form['status']['#group'])) {
    $form['status']['#group'] = 'footer';
  }
  if (!empty($form['actions'])) {
    $form['actions']['#weight'] = 1000;
  }
  if (!empty($form['advanced'])) {
    $form['advanced']['#type'] = 'accordion';
    $form['advanced']['#wrapper_attributes']['class'][] = '!m-0';
  }

  if (!empty($form['meta'])) {
    $form['meta']['#type'] = 'container';
    $form['meta']['#access'] = TRUE;
    $form['meta']['#attributes']['class'][] = 'p-card text-sm !m-0';

    if (isset($form['meta']['published'])) {
      $form['meta']['#attributes']['class'][] = '!pt-0';
      if ($form['meta']['published']['#type'] === 'html_tag' && isset($form['meta']['published']['#value'])) {
        $form['meta']['published'] = [
          '#type' => 'item',
          '#markup' => $form['meta']['published']['#value'],
        ];
      }
      $form['meta']['published']['#wrapper_attributes']['class'][] = 'mt-0';
      $form['meta']['published']['#wrapper_attributes']['class'][] = '-ml-form-item';
      $form['meta']['published']['#wrapper_attributes']['class'][] = '-mr-form-item';
      $form['meta']['published']['#wrapper_attributes']['class'][] = 'px-form-item';
      $form['meta']['published']['#wrapper_attributes']['class'][] = 'py-4';
      $form['meta']['published']['#wrapper_attributes']['class'][] = 'font-bold';
      $form['meta']['published']['#wrapper_attributes']['class'][] = 'text-xl';
      $form['meta']['published']['#wrapper_attributes']['class'][] = 'rounded-t-sm';
      if ($entity->isNew()) {
        $form['meta']['published']['#access'] = TRUE;
        $form['meta']['published']['#markup'] = neo_icon('Draft');
        $form['meta']['published']['#wrapper_attributes']['class'][] = 'bg-base-500';
        $form['meta']['published']['#wrapper_attributes']['class'][] = 'text-base-500-content';
      }
      elseif ($entity instanceof EntityPublishedInterface) {
        if ($entity instanceof EntityPublishedInterface && $entity->isPublished()) {
          $form['meta']['published']['#markup'] = neo_icon('Published');
          $form['meta']['published']['#wrapper_attributes']['class'][] = 'bg-success-500';
          $form['meta']['published']['#wrapper_attributes']['class'][] = 'text-success-500-content';
        }
        else {
          $form['meta']['published']['#markup'] = neo_icon('Unpublished');
          $form['meta']['published']['#wrapper_attributes']['class'][] = 'bg-warning-500';
          $form['meta']['published']['#wrapper_attributes']['class'][] = 'text-warning-500-content';
        }
      }
    }
  }

  if ($statusKey = $entity->getEntityType()->getKey('status')) {
    if (!empty($form[$statusKey])) {
      $form[$statusKey]['#group'] = 'meta';
      $form[$statusKey]['widget']['value']['#neo_size'] = 'sm';
    }
  }

  if (!empty($form['revision_information'])) {
    $form['revision_information']['#type'] = 'container';
    $form['revision_information']['#group'] = 'meta';
    $form['revision_information']['#attributes']['class'][] = 'entity-meta--revision';
  }
}

/**
 * Implements hook_preprocess_form().
 */
function neo_back_preprocess_form(&$variables) {
  $variables['inner_attributes']->addClass('bg-default');
}

/**
 * Implements template_preprocess_views_view().
 */
function neo_back_preprocess_views_view(&$variables) {
  foreach ([
    'header',
    'footer',
    'empty',
  ] as $region) {
    if (!empty($variables[$region]) && is_array($variables[$region])) {
      $count = 0;
      foreach ($variables[$region] as $key => &$item) {
        if (is_array($item) && isset($item['#type'])) {
          switch ($item['#type']) {
            case 'link':
              $count++;
              break;
          }
        }
      }
      if (count($variables[$region]) === $count) {
        $variables[$region . '_attributes']['class'][] = 'flex gap-2 flex-wrap';
      }
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function neo_back_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['secondary'])) {
    // Views exposed filter support.
    $form['secondary']['#attributes']['class'][] = 'form--inline-none';
    $form['secondary']['#weight'] = 1000;
    $form['secondary']['#neo_size'] = 'xs';
    $form['secondary']['#neo_size_inherit'] = FALSE;
  }
}
