<?php

/**
 * @file
 * Functions to support theming in the neo theme.
 */

use Drupal\Core\Entity\EntityFormInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityPublishedInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function neo_back_theme() {
  return [
    'entity_edit_form' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for \Drupal\node\NodeForm.
 *
 * Changes vertical tabs to container.
 */
function neo_back_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\Core\Entity\EntityFormInterface $form_object */
  $form_object = $form_state->getFormObject();
  if ($form_object instanceof EntityFormInterface) {
    // Only apply if we have no neo style set.
    if (empty($form['#no_entity_edit_form'])) {
      $entity = $form_object->getEntity();
      $form['#theme'] = ['entity_edit_form'];
      neo_back_form_meta($form, $form_state, $entity);
    }
  }
  $form['#neo_style'] = $form['#neo_style'] ?? 'card';

  switch ($form_id) {
    case 'user_admin_permissions':
      $form['actions']['#neo_style'] = 'sticky';
      break;
  }
}

/**
 * Implements meta alterations.
 */
function neo_back_form_meta(&$form, FormStateInterface $form_state, EntityInterface $entity) {
  if (!empty($form['status'])) {
    $form['status']['#group'] = 'footer';
  }
  if (!empty($form['actions'])) {
    $form['actions']['#weight'] = 1000;
  }
  if (!empty($form['advanced'])) {
    $form['advanced']['#type'] = 'accordion';
    $form['advanced']['#wrapper_attributes']['class'][] = '!m-0';
  }

  if (!empty($form['meta'])) {
    $form['meta']['#type'] = 'container';
    $form['meta']['#access'] = TRUE;
    $form['meta']['#attributes']['class'][] = 'p-card text-sm';

    if (isset($form['meta']['published'])) {
      $form['meta']['#attributes']['class'][] = '!pt-0';
      if ($form['meta']['published']['#type'] === 'html_tag' && isset($form['meta']['published']['#value'])) {
        $form['meta']['published'] = [
          '#type' => 'item',
          '#markup' => $form['meta']['published']['#value'],
        ];
      }
      $form['meta']['published']['#wrapper_attributes']['class'][] = 'mt-0';
      $form['meta']['published']['#wrapper_attributes']['class'][] = '-ml-form-item';
      $form['meta']['published']['#wrapper_attributes']['class'][] = '-mr-form-item';
      $form['meta']['published']['#wrapper_attributes']['class'][] = 'px-form-item';
      $form['meta']['published']['#wrapper_attributes']['class'][] = 'py-4';
      $form['meta']['published']['#wrapper_attributes']['class'][] = 'font-bold';
      $form['meta']['published']['#wrapper_attributes']['class'][] = 'text-xl';
      $form['meta']['published']['#wrapper_attributes']['class'][] = 'rounded-t-sm';
      if ($entity->isNew()) {
        $form['meta']['published']['#access'] = TRUE;
        $form['meta']['published']['#markup'] = neo_icon('Draft');
        $form['meta']['published']['#wrapper_attributes']['class'][] = 'bg-base-500';
        $form['meta']['published']['#wrapper_attributes']['class'][] = 'text-base-content-500';
      }
      elseif ($entity instanceof EntityPublishedInterface) {
        if ($entity instanceof EntityPublishedInterface && $entity->isPublished()) {
          $form['meta']['published']['#markup'] = neo_icon('Published');
          $form['meta']['published']['#wrapper_attributes']['class'][] = 'bg-success-500';
          $form['meta']['published']['#wrapper_attributes']['class'][] = 'text-success-content-500';
        }
        else {
          $form['meta']['published']['#markup'] = neo_icon('Unpublished');
          $form['meta']['published']['#wrapper_attributes']['class'][] = 'bg-warning-500';
          $form['meta']['published']['#wrapper_attributes']['class'][] = 'text-warning-content-500';
        }
      }
    }
  }

  if (!empty($form['revision_information'])) {
    $form['revision_information']['#type'] = 'container';
    $form['revision_information']['#group'] = 'meta';
    $form['revision_information']['#attributes']['class'][] = 'entity-meta--revision';
  }
}
